### ISSUE TITLE
Unity 2019.1.9f1 freezes

### ISSUE THREAD

**Issue by yosun** [alessandroTironi/Unity-DialogflowV2Agents#1]
curious which version of unity you tested this with

**Comment by Mrmiffo** [comment]
This project worked perfectly for me using Unity 2018.3.3f1.

**Comment by alessandroTironi** [comment]
Hi, sorry for the very late response, I totally missed this issue. I built and tested the package with Unity 2019.1.5, but I am planning to update the engine version to check for new errors.

**Comment by alessandroTironi** [comment]
Hi, I updated to Unity 2019.2.17 and I had no issues running the sample scene. I am closing this issue, if you still have problems please report the exact error message you got.
