### ISSUE TITLE
Not working on Android

### ISSUE THREAD

**Issue by Mrmiffo** [alessandroTironi/Unity-DialogflowV2Agents#2]
The Newtonsoft.Json.dll does not work on Android. However, replacing this .dll file with the "JSON .NET For Unity" package (free) from Unity Asset Store (https://assetstore.unity.com/packages/tools/input-management/json-net-for-unity-11347) resolves this. No change in the code base of the plugin itself needed, even the namespace is correct.

**Comment by binolgeorge** [comment]
I couldn't find Syrus.Plugins.DialogflowV2Agents.dll.??

**Comment by alessandroTironi** [comment]
Hi @Mrmiffo , thanks for the segnalation and solution. After having tested both the issue replication and the solution, I pushed an updated version of the plugin with the correct Newtonsoft.Json.dll file. Sorry for the late response, but I had not received notifications for the issues!
