### ISSUE TITLE
Google Cloud Platform

### ISSUE THREAD

**Issue by GaryQuahVizioFly** [alessandroTironi/Unity-DialogflowV2Agents#5]
Hi,  I have downloaded the project, and noted in the instructions that we have to have a " .p12 private access key file associated to the GCP service account you want to use for the chatbot client" . Regarding this, from what Ive seen, in order to use GCP service account, we have to pay $300 a month, is there a free alternative to this? Cheers

**Comment by israteneda** [comment]
GCP has a free tier so you shouldn't pay $300 a month. GCP offer to you $300 of credit for one year. Maybe it's a little confuse but if you search more you'll find what I am talking about :)
