### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by GaryQuahVizioFly** [alessandroTironi/Unity-DialogflowV2Agents#6]
Hi, this is more of a question rather than an issue, I can use this project to simply convert text to speech and speech to text without getting a response from the bot right?

**Comment by israteneda** [comment]
I think that there are better options to achieve your goal, the main purpose of this project is connected Dialogflow with Unity

**Comment by alessandroTironi** [comment]
Hi @GaryQuahVizioFly, the answer is no: both text to speech and speech to text stuff is done by the bot on Google servers, so you are forced to rely on that.
However, as @israteneda said, I suggest you to look for ad-hoc libraries, since using DF just for text to speech would be quite tedious.
